we will use the stats of players to predct how many mvp points they would win , or more precisly what share of mvp votes they get , this would help determining wether the player wins or not at the end

In [1]:
import pandas as pd

In [2]:
stats =pd.read_csv('player_mvp_stats.csv')

In [3]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14693,14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14694,14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14695,14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14696,14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [4]:
del stats['Unnamed: 0']

In [5]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          59
3P            0
3PA           0
3P%        2086
2P            0
2PA           0
2P%         100
eFG%         59
FT            0
FTA           0
FT%         521
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

the null values are present in 3pt percentage and ft percentage , this could be because a player has not attempted any 3pt shots in the season so there is no value for that number , we could replace them wiht 0 instead if this is the case

In [8]:
stats[pd.isnull(stats['3P%'])][['Player','3PA']]

                 Player  3PA
2        Elden Campbell  0.0
3         Irving Thomas  0.0
18           Jack Haley  0.0
20          Keith Owens  0.0
30      Benoit Benjamin  0.0
...                 ...  ...
14666    Evan Eschmeyer  0.0
14667  Gheorghe Mureșan  0.0
14669     Jim McIlvaine  0.0
14675  Mark Hendrickson  0.0
14676      Michael Cage  0.0

[2086 rows x 2 columns]

we can see that when 3pa is 0 , 3p% is null, lets check it for ft percent

In [9]:
stats[pd.isnull(stats['FT%'])][['Player','FTA']]

                Player  FTA
77          John Coker  0.0
92        Jason Sasser  0.0
103    Adrian Caldwell  0.0
119       Bruno Šundov  0.0
158     Jamal Robinson  0.0
...                ...  ...
14556    Mark McNamara  0.0
14584      Luke Zeller  0.0
14637      Myron Brown  0.0
14659      Malcolm Lee  0.0
14693      Steve Novak  0.0

[521 rows x 2 columns]

now replace all null values with zero

In [10]:
stats=stats.fillna(0)

In [11]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14697 entries, 0 to 14696
Data columns (total 41 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   14697 non-null  object
 1   Pos      14697 non-null  object
 2   Age      14697 non-null  int64
 3   Tm       14697 non-null  object
 4   G        14697 non-null  int64
 5   GS       14697 non-null  int64
 6   MP       14697 non-null  float64
 7   FG       14697 non-null  float64
 8   FGA      14697 non-null  float64
 9   FG%      14697 non-null  float64
 10  3P       14697 non-null  float64
 11  3PA      14697 non-null  float64
 12  3P%      14697 non-null  float64
 13  2P       14697 non-null  float64
 14  2PA      14697 non-null  float64
 15  2P%      14697 non-null  float64
 16  eFG%     14697 non-null  float64
 17  FT       14697 non-null  float64
 18  FTA      14697 non-null  float64
 19  FT%      14697 non-null  float64
 20  ORB      14697 non-null  float64
 21  DRB      14697 non-null  float64
 22  TRB      14697 non-null  float64
 23  AST      14697 non-null  float64
 24  STL      14697 non-null  float64
 25  BLK      14697 non-null  float64
 26  TOV      14697 non-null  float64
 27  PF       14697 non-null  float64
 28  PTS      14697 non-null  float64
 29  Year     14697 non-null  int64
 30  Pts Won  14697 non-null  float64
 31  Pts Max  14697 non-null  float64
 32  Share    14697 non-null  float64
 33  Team     14697 non-null  object
 34  W        14697 non-null  int64
 35  L        14697 non-null  int64
 36  W/L%     14697 non-null  float64
 37  GB       14697 non-null  float64
 38  PS/G     14697 non-null  float64
 39  PA/G     14697 non-null  float64
 40  SRS      14697 non-null  float64
dtypes: float64(31), int64(6), object(4)
memory usage: 4.6+ MB

In [12]:
stats.isnull().sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
dtype: int64

now all null values have been removed

In [13]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

we will use numeric attributes to predict mvp, remove attributes like team , player name position etc , and also remove the stats about mvp shares won from the predictors set as they are the target variables

In [14]:
predictors=['Age','G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year','W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [15]:
train = stats[stats["Year"]<2022]
test = stats[stats['Year']==2022]

ridge regression which is a modification of linear regression will be used here
this reduces overfitting due to multi collinearity of attributes by introducing a regularization parameter while calculating sum of squared error

In [16]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=0.1)

In [18]:
reg.fit(train[predictors],train['Share'])

Ridge(alpha=0.1)

In [19]:
predictions=reg.predict(test[predictors])

In [21]:
predictions=pd.DataFrame(predictions,columns=['predictions'],index=test.index)

In [22]:
predictions

       predictions
648       0.012934
649      -0.028143
650      -0.006163
651       0.016564
652      -0.004820
...            ...
12508    -0.019380
12509    -0.010197
12510     0.003810
12511     0.001162
12512    -0.057007

[605 rows x 1 columns]

In [24]:
combination=pd.concat([test[['Player','Share']],predictions],axis=1)

In [25]:
combination

                Player  Share  predictions
648       Aaron Gordon    0.0     0.012934
649      Austin Rivers    0.0    -0.028143
650            Bol Bol    0.0    -0.006163
651       Bones Hyland    0.0     0.016564
652        Bryn Forbes    0.0    -0.004820
...                ...    ...          ...
12508     Micah Potter    0.0    -0.019380
12509  Rodney McGruder    0.0    -0.010197
12510        Saben Lee    0.0     0.003810
12511       Saddiq Bey    0.0     0.001162
12512   Trayvon Palmer    0.0    -0.057007

[605 rows x 3 columns]

In [26]:
combination.sort_values("Share",ascending=False).head(10)

                      Player  Share  predictions
663             Nikola Jokić  0.875     0.190365
837              Joel Embiid  0.706     0.190462
11678  Giannis Antetokounmpo  0.595     0.219409
907             Devin Booker  0.216     0.091309
11469            Luka Dončić  0.146     0.157395
1179            Jayson Tatum  0.043     0.095903
12226              Ja Morant  0.010     0.120508
6398           Stephen Curry  0.004     0.093137
905               Chris Paul  0.002     0.078328
8241            LeBron James  0.001     0.157827

In [28]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination['Share'],combination['predictions'])

0.002240037320173767

this isnt a good error metric as we dont actualy care about the actual number instead we need the ranking of players acc to this metric , also a vast majority of values in this are 0 so it would make using mean squared error not suitable as it calculates the raw differnce in values squared

we dont care if the model predicts the bottom 380 or so players mvp shares as they would be zero ,most of the players do not edn  up receiving any votes , we want our model to be accurate for the top players

In [39]:
combination=combination.sort_values('Share',ascending=False)
combination['Rk']=list(range(1,combination.shape[0]+1))
# adding rank column to combinations df and also sorting them in order of share

In [40]:
combination.head(10)

                      Player  Share  predictions  Rk  Predicted Rk
663             Nikola Jokić  0.875     0.190365   1             3
837              Joel Embiid  0.706     0.190462   2             2
11678  Giannis Antetokounmpo  0.595     0.219409   3             1
907             Devin Booker  0.216     0.091309   4            17
11469            Luka Dončić  0.146     0.157395   5             5
1179            Jayson Tatum  0.043     0.095903   6            13
12226              Ja Morant  0.010     0.120508   7             7
6398           Stephen Curry  0.004     0.093137   8            15
905               Chris Paul  0.002     0.078328   9            21
3938           DeMar DeRozan  0.001     0.099240  10            11

In [41]:
combination=combination.sort_values('predictions',ascending=False)
combination['Predicted Rk']=list(range(1,combination.shape[0]+1))
# sorting by predicted share value

In [42]:
combination.head(10)

                      Player  Share  predictions   Rk  Predicted Rk
11678  Giannis Antetokounmpo  0.595     0.219409    3             1
837              Joel Embiid  0.706     0.190462    2             2
663             Nikola Jokić  0.875     0.190365    1             3
8241            LeBron James  0.001     0.157827   12             4
11469            Luka Dončić  0.146     0.157395    5             5
6185            Kevin Durant  0.001     0.140626   11             6
12226              Ja Morant  0.010     0.120508    7             7
11820             Trae Young  0.000     0.109246  406             8
8231           Anthony Davis  0.000     0.107306  407             9
836             James Harden  0.000     0.103584  408            10

i want to create an error metric that sees if the actual top 5 mvp finishers were predicted in the top 5 , 

for players correctly ranked there is no penalty, but if not, we see how further down they are predicted than their actual ranking , and the larger this is , the more will be the penalty